### ISSUE TITLE
Script compilation errors and script size increase after bumping from 1.27 to 1.45

### ISSUE THREAD

**Issue by jstolarek** [input-output-hk/plutus#7088]
I recently bumped Plutus dependencies in one IOG's projects from Plutus 1.27 to Plutus 1.45.  After fixing Haskell compilation errors and running the project's testsuite I noticed two problems:

  1. Majority of the scripts fails to compile with an error:

     > Exception: Error: Unexpected error during compilation, please report this to the Plutus team: Use of fromString @ PlutusTx.Builtins.Internal. BuiltinByteString with inscrutable content: TrustlessSidechain.Versioning.approvedByGovernance2

  2. Those few scripts that do compile have their sizes increased by about 10% when serialized.

I prepared a test case that allows to reproduce the problem.  It relies on GHC 9.6.6 and requires additional Cardano-specific libraries to be installed in the system (`libsodium`, `libblst`) and available on `PKG_CONFIG_PATH` and `LD_LIBRARY_PATH` paths.  There is also Nix configuration available in the repository, but I have not tested it and don't know whether using it allows to compile the project with bumped Plutus dependencies.  That being said, begin by cloning the repository and running a version of the code that uses plutus 1.27, to verify that the base case works as expected

  1. `git clone git@github.com:jstolarek/partner-chains-smart-contracts.git`
  2. `cd partner-chains-smart-contracts/onchain`
  3. `git checkout plutus-1.27`
  4. `cabal test script-size`

Testsuite in step (4) compiles and serializes Plutus scripts in the project and compares their sizes against a defined limit.  Any increase in compiled script size is reported as an error.  At this point all tests should pass.  Now checkout the code with dependencies bumped to plutus 1.45 and re-run the tests:

  1. `git checkout plutus-1.45`
  4. `cabal test script-size`

All tests should fail, 6 of them due to compilation errors, the other 3 due to size increase.  My efforts to debug the problem originally started with trying to understand the size increase of those scripts that compile.  I've spent a couple of days on this but didn't really get anywhere.  Only when writing this report I have realized the compilation issues with the other six scripts.  This I have not attempted to debug at all and it is entirely possible the fault lies in the project code itself.  As for size increase in compiled scripts, I speculate this is a regression, though it is also entirely possible that this is a result of some optimization that trades compiled size for runtime performance.

**Comment by jstolarek** [comment]
Thanks. I made a couple of changes to test project:

  * I bumped the dependency of Plutus to latest version 1.46.
  * I dropped the dependency on cardano-api and deleted corresponding code, since it is not relevant for the problem at hand
  * I also decided to comment out tests that fail with `fromString` error. Again, not my primary concern here and sadly I do not have time to spend on debugging these. As a result there are now only two test cases in the `script-size` test suite, but these should suffice.
  * I turned on `conservative-optimisation` flag in the relevant source file. This brings down the sizes compared to earlier version using plutus 1.45 and no extra flags, but these sizes are still larger than with plutus 1.27 and no extra flags.

At this point, I sadly have no time to further dig into the problem and will just accept these size increases in my project. I am leaving it to the Plutus team to decide how to deal with the bug report. This might be an interesting real life use case to study, but it also might be best to just close this as wontfix.

**Comment by colll78** [comment]
You don't want conservative-optimization, you want size-oriented optimization. In 1.27 it was regularly sacrificing larger ex-unit cost for lower script size (aggressive hoisting etc), later the value scale has shifted, conservative optimization will not revert to that. More flag options is always better and a feature request for a flag that always performs size optimizations regardless of their tradeoffs might be what you are looking for.

**Comment by ana-pantilie** [comment]
Thank you @colll78 for helping out with this!

@jstolarek once you find time to debug this further feel free to reopen this issue if you find any specific problem regarding compilation or a performance regression. Until then, since the team doesn't really have anything concrete to work on here, I'm closing this.
